# file: text.py
# vim:fileencoding=utf-8:ft=python:fdm=marker
# Copyright © 2011-2021 R.F. Smith <rsmith@xs4all.nl>. All rights reserved.
# SPDX-License-Identifier: BSD-2-Clause
# Created: 2011-03-27 13:59:17 +0200
# Last modified: 2023-09-02T17:04:13+0200
"""Text output routines for lamprop."""

from .version import __version__
import lp.core as core

# Data


def out(lam, eng, mat, fea):  # {{{1
    """Return the output as a list of lines."""
    lines = [
        f"Generated by lamprop version {__version__}",
        f"laminate: {lam.name}",
        f"thickness: {lam.thickness:.2f} mm, density: {lam.ρ:4.2f} g/cm³",
        f"fiber volume fraction: {lam.vf*100:.3g}%, "
        f"fiber weight fraction: {lam.wf*100:.3g}%",
        f"laminate weight: {lam.fiber_weight + lam.resin_weight:.0f} g/m², "
        f"resin consumption: {lam.resin_weight:.0f} g/m²",
        "num weight angle   vf fiber",
        "    [g/m²]   [°]  [%]",
    ]
    ln = 1
    for la in lam.layers:
        if isinstance(la, str):
            lines.append(la)
            continue
        lines.append(
            f"{ln:3} {la.fiber_weight:6g} {la.angle:5g} {la.vf * 100:4.3g} "
            f"{la.fiber.name}"
        )
        ln += 1
    if eng:
        lines += _engprop(lam)
    if mat:
        lines += _matrices(lam)
    if fea:
        lines += _fea(lam)
    lines.append("")
    return lines


def _engprop(l):  # {{{1
    """Return the engineering properties as a plain text table in the form of
    a list of lines."""
    lines = ["In-plane engineering properties:"]
    lines += [
        f"E_x  = {l.Ex:.0f} MPa, E_y  = {l.Ey:.0f} MPa, E_z  = {l.Ez:.0f} MPa ",
        f"G_xy  = {l.Gxy:.0f} MPa, G_xz  = {l.Gxz:.0f} MPa, G_yz  = {l.Gyz:.0f} MPa ",
        f"ν_xy = {l.νxy:7.5f}",
        f"α_x = {l.αx:9.4g} K⁻¹, α_y = {l.αy:9.4g} K⁻¹",
    ]
    lines.append("Engineering properties derived from 3D stiffness matrix:")
    lines.append(f"E_x = {l.tEx:.0f} MPa, E_y = {l.tEy:.0f} MPa, E_z = {l.tEz:.0f} MPa")
    lines.append(
        f"G_xy = {l.tGxy:.0f} MPa, G_xz = {l.tGxz:.0f} MPa, G_yz = {l.tGyz:.0f} MPa"
    )
    lines.append(f"ν_xy = {l.tνxy:.3f}, ν_xz = {l.tνxz:.3f}, ν_yz = {l.tνyz:.3f}")
    return lines


def _matrices(l):  # {{{1
    """Return the ABD, abd, H and h matrices as plain text."""
    lines = ["In-plane stiffness (ABD) matrix:"]
    for n in range(6):
        lines.append(
            f"|{l.ABD[n][0]:< 10.4} {l.ABD[n][1]:< 10.4} {l.ABD[n][2]:< 10.4} "
            f"{l.ABD[n][3]:< 10.4} {l.ABD[n][4]:< 10.4} {l.ABD[n][5]:< 10.4}|"
        )
    lines.append("Transverse (H) stiffness matrix:")
    for n in range(2):
        lines.append(f"|{l.H[n][0]:< 10.4} {l.H[n][1]:< 10.4}|")
    lines += ["3D stiffness tensor [C], contracted notation:"]
    lines.append("(indices for stress/strain are in the order 11, 22, 33, 23, 13, 12)")
    for row in l.C:
        lines.append(
            f"|{row[0]:< 10.4} {row[1]:< 10.4} {row[2]:< 10.4} "
            f"{row[3]:< 10.4} {row[4]:< 10.4} {row[5]:< 10.4}|"
        )
    return lines


def _fea(l):  # {{{1
    """Return the material data for FEA."""
    lines = ["** Material data for CalculiX / Abaqus (SI units):"]
    D = core.toabaqusi(l.C)
    lines.append(f"*MATERIAL,NAME={l.name}")
    if core.isortho(l.C):
        # Convert to abaqus format and SI units
        lines.append("*ELASTIC,TYPE=ORTHO")
        lines.append(
            f"{D[0][0]:.4g},{D[0][1]:.4g},{D[1][1]:.4g},"
            f"{D[0][2]:.4g},{D[1][2]:.4g},{D[2][2]:.4g},"
            f"{D[3][3]:.4g},{D[4][4]:.4g},"
        )
        lines.append(f"{D[5][5]:.4g},293")
    else:
        lines.append("*ELASTIC,TYPE=ANISO")
        lines.append(
            f"{D[0][0]:.4g},{D[0][1]:.4g},{D[1][1]:.4g},"
            f"{D[0][2]:.4g},{D[1][2]:.4g},{D[2][2]:.4g},"
            f"{D[0][3]:.4g},{D[1][3]:.4g},"
        )
        lines.append(
            f"{D[2][3]:.4g},{D[3][3]:.4g},{D[0][4]:.4g},"
            f"{D[1][4]:.4g},{D[2][4]:.4g},{D[3][4]:.4g},"
            f"{D[4][4]:.4g},{D[0][5]:.4g},"
        )
        lines.append(
            f"{D[1][5]:.4g},{D[2][5]:.4g},{D[3][5]:.4g},"
            f"{D[4][5]:.4g},{D[5][5]:.4g},293"
        )
    lines.append("*DENSITY")
    lines.append(f"{l.ρ*1000:.0f}")
    return lines
